#!/usr/bin/env node
/**
 * One line per source file, so an agent greps this instead of opening the tree.
 *
 *   node scripts/code-index.mjs
 *
 * Writes docs/code-index.md. Do not read the file whole. Search it:
 *   rg -n "raid" docs/code-index.md
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const src = join(root, "src");
const out = join(root, "docs/code-index.md");

function walk(dir, acc) {
  for (const name of readdirSync(dir)) {
    if (name === "node_modules" || name.startsWith(".")) continue;
    const path = join(dir, name);
    const st = statSync(path);
    if (st.isDirectory()) walk(path, acc);
    else if (/\.(ts|tsx)$/.test(name)) acc.push(path);
  }
  return acc;
}

function purpose(text) {
  const block = text.match(/^\s*\/\*\*?([\s\S]*?)\*\//);
  if (!block) return "";
  const line = block[1]
    .split("\n")
    .map((l) => l.replace(/^\s*\*\s?/, "").trim())
    .find((l) => l && !l.startsWith("@"));
  return (line || "").replace(/\|/g, "/").slice(0, 110);
}

function exportsOf(text) {
  const names = [];
  const re = /export\s+(?:async\s+)?(?:function|const|class|type|interface|enum)\s+([A-Za-z0-9_]+)/g;
  let m;
  while ((m = re.exec(text)) && names.length < 6) names.push(m[1]);
  return names.join(", ");
}

const files = walk(src, []).sort();
const rows = files.map((path) => {
  const text = readFileSync(path, "utf8");
  return {
    path: relative(root, path),
    purpose: purpose(text),
    exports: exportsOf(text),
  };
});

const groups = new Map();
for (const row of rows) {
  const parts = row.path.split("/");
  const key = parts.length > 2 ? parts.slice(0, 3).join("/") : parts.slice(0, 2).join("/");
  if (!groups.has(key)) groups.set(key, []);
  groups.get(key).push(row);
}

const lines = [
  "# Code index",
  "",
  "Search this. Do not read it whole. One line is the file, its exports, and the first sentence of its header.",
  "",
  "```",
  "rg -n \"raid|entry|floor\" docs/code-index.md",
  "```",
  "",
  `Generated by \`node scripts/code-index.mjs\`. ${rows.length} files. Regenerate after a file is added or renamed.`,
  "",
];
for (const [key, group] of groups) {
  lines.push(`## ${key}`);
  lines.push("");
  for (const row of group) {
    lines.push(`- \`${row.path}\` — ${row.exports || "no named export"}${row.purpose ? ` — ${row.purpose}` : ""}`);
  }
  lines.push("");
}
writeFileSync(out, lines.join("\n"));
console.log(`code-index: ${rows.length} files → ${relative(root, out)}`);
