/**
 * Invariants on src/data/learn-cases.json — the real-tape walkthroughs.
 *
 * The file is regenerated by build-learn-cases.mjs, and a regeneration that
 * quietly breaks causality or arithmetic would teach a lie with perfect
 * confidence. So the properties that make a case honest are asserted here,
 * not assumed: the decision bar is where the case says it is, every "future"
 * bar is strictly after it, the chase stop is on the correct side of the
 * entry, the realised R agrees with the outcome word, and every decision
 * sits in the window the desk actually trades.
 *
 * Run: npx tsx scripts/verify-cases.mjs
 */
import { readFileSync } from "node:fs";

const { APLUS_RULES } = await import("../src/lib/aplus/config.ts");

const file = JSON.parse(readFileSync("src/data/learn-cases.json", "utf8"));
let pass = 0;
let fail = 0;
const ok = (label, cond, extra = "") => {
  if (cond) pass++;
  else {
    fail++;
    console.log(`  FAIL ${label}${extra ? ` — ${extra}` : ""}`);
  }
};

const etMinutes = (t) => {
  const p = new Intl.DateTimeFormat("en-US", { timeZone: "America/New_York", hour: "2-digit", minute: "2-digit", hour12: false })
    .formatToParts(new Date(t));
  const h = Number(p.find((x) => x.type === "hour").value);
  const m = Number(p.find((x) => x.type === "minute").value);
  return h * 60 + m;
};

console.log(`cases file: built ${file.builtAt}, history ${file.historyCapturedAt}, ${file.cases.length} cases, pool ${JSON.stringify(file.pool)}`);

ok("file has cases", file.cases.length > 0);
ok("pool tally present", file.pool && typeof file.pool.takes === "number");
ok("case ids unique", new Set(file.cases.map((c) => c.id)).size === file.cases.length);

for (const c of file.cases) {
  const tag = `${c.id}`;
  const d = c.bars[c.decisionIndex];
  ok(`${tag}: decisionIndex points at the decision bar`, d && d.t === c.decisionT);
  ok(`${tag}: bars strictly ascending`, c.bars.every((b, i) => i === 0 || b.t > c.bars[i - 1].t));
  ok(`${tag}: everything after the decision is strictly later`, c.bars.slice(c.decisionIndex + 1).every((b) => b.t > c.decisionT));
  ok(`${tag}: everything before the decision is strictly earlier`, c.bars.slice(0, c.decisionIndex).every((b) => b.t < c.decisionT));
  ok(`${tag}: has future bars to reveal`, c.bars.length - 1 - c.decisionIndex >= 8, `${c.bars.length - 1 - c.decisionIndex}`);
  ok(`${tag}: candles well-formed`, c.bars.every((b) => b.h >= Math.max(b.o, b.c) && b.l <= Math.min(b.o, b.c)));
  const m = etMinutes(c.decisionT);
  ok(`${tag}: decision inside NY AM 09:45–11:00 ET`, m >= 9 * 60 + 45 && m <= 11 * 60, `${m}`);
  ok(`${tag}: has steps and a lesson`, c.steps.length >= 6 && c.lesson.length > 40);
  ok(`${tag}: word is TAKE/WAIT/STAND`, ["TAKE", "WAIT", "STAND"].includes(c.word));
  ok(`${tag}: confluence at or above the floor`, c.confluence >= APLUS_RULES.confluenceFloor, `${c.confluence}`);

  const plans = [c.plan, c.chase?.plan].filter(Boolean);
  for (const p of plans) {
    const long = p.side === "long";
    ok(`${tag}: stop on the correct side of entry`, long ? p.stop < p.entry : p.stop > p.entry);
    ok(`${tag}: riskPts equals |entry − stop|`, Math.abs(p.riskPts - Math.abs(p.entry - p.stop)) < 0.011, `${p.riskPts} vs ${Math.abs(p.entry - p.stop)}`);
    if (p.t1 != null) ok(`${tag}: T1 is in front of the entry`, long ? p.t1 > p.entry : p.t1 < p.entry);
    if (p.t1 != null && p.rr1 != null) ok(`${tag}: rr1 = |T1 − entry| / risk`, Math.abs(p.rr1 - Math.abs(p.t1 - p.entry) / p.riskPts) < 0.011);
  }

  const outcomes = [];
  if (c.outcome !== "stand") outcomes.push({ o: c.outcome, r: c.r, who: "trade" });
  if (c.chase) outcomes.push({ o: c.chase.outcome, r: c.chase.r, who: "chase" });
  for (const { o, r, who } of outcomes) {
    if (o === "win") ok(`${tag}: ${who} win has positive R`, r != null && r > 0.05, `${r}`);
    if (o === "loss") ok(`${tag}: ${who} loss has negative R`, r != null && r < -0.05, `${r}`);
    if (o === "loss") ok(`${tag}: ${who} loss never worse than the stop (−1R) plus scale-out`, r >= -1.0001, `${r}`);
    if (o === "scratch") ok(`${tag}: ${who} scratch is near flat`, r != null && Math.abs(r) <= 0.05, `${r}`);
  }

  // A stand case with a correct-polarity raid must carry a chase, so the
  // cost of not waiting is always shown rather than sometimes.
  if (c.outcome === "stand" && c.side) {
    const raidStep = c.steps.find((s) => /^3/.test(s.title));
    const polarityOk = raidStep && (c.side === "short" ? /buyside raid/.test(raidStep.body) : /sellside raid/.test(raidStep.body));
    if (polarityOk) ok(`${tag}: refused setup with a correct-polarity raid carries a chase counterfactual`, c.chase != null);
  }
}

// Honesty of the set: it must not be all winners, and it must include the
// desk's refusals — the point is the decision, not the highlight reel.
const chaseLosses = file.cases.filter((c) => c.chase?.outcome === "loss").length;
const chaseWins = file.cases.filter((c) => c.chase?.outcome === "win").length;
ok("teaching set includes chase losses", chaseLosses > 0, `${chaseLosses}`);
ok("teaching set is not curated to a single outcome", chaseLosses + chaseWins === 0 || (chaseLosses > 0 && chaseWins >= 0));
ok("both books represented", new Set(file.cases.map((c) => c.symbol)).size === 2);
ok("both sides represented", new Set(file.cases.map((c) => c.side)).size >= 2);
ok("cases span more than one week", (Math.max(...file.cases.map((c) => c.decisionT)) - Math.min(...file.cases.map((c) => c.decisionT))) > 7 * 86400000);

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
