#!/usr/bin/env python
"""
Black-Scholes from first principles — the independent oracle for src/lib/room/option-math.ts.

    python scripts/oracle/bs_oracle.py > src/data/oracle-bs-grid.json     # regenerate the committed fixture
    python scripts/oracle/bs_oracle.py --check                            # exit 1 unless the committed fixture is what this prints

WHY A SECOND IMPLEMENTATION
The desk prices every option ticket on `blackScholes` (r = 0, European, VIX-scaled IV) with a polynomial normal CDF
(Abramowitz & Stegun 7.1.26, |error| < 7.5e-8). The checks that existed were parity — which holds by construction, the put is
defined by parity — and "an ATM delta is within 0.02 of 0.5". This file is written from the textbook formulas with the CDF taken
from the C library's erfc (exact to about one ulp), computes the put from its OWN formula (not parity), and cross-checks its CDF
against the standard library's statistics.NormalDist at generation time, so a disagreement with the TypeScript is a finding about
one of the two and the fixture says which numbers to look at. Standard library only: nothing to install.

Conventions match the desk's: r = 0, no dividends, thetaDay = value lost per CALENDAR day per share (a positive number), delta
call = N(d1), put = N(d1) - 1.
"""
import json
import math
import sys
from statistics import NormalDist

ND = NormalDist()


def ncdf(x: float) -> float:
    return 0.5 * math.erfc(-x / math.sqrt(2.0))


def npdf(x: float) -> float:
    return math.exp(-0.5 * x * x) / math.sqrt(2.0 * math.pi)


def bs(s: float, k: float, t: float, v: float, kind: str):
    sq = math.sqrt(t)
    d1 = (math.log(s / k) + 0.5 * v * v * t) / (v * sq)
    d2 = d1 - v * sq
    if kind == "CALL":
        price = s * ncdf(d1) - k * ncdf(d2)
        delta = ncdf(d1)
    else:
        price = k * ncdf(-d2) - s * ncdf(-d1)  # its own formula, not parity
        delta = ncdf(d1) - 1.0
    theta_day = s * npdf(d1) * v / (2.0 * sq) / 365.0
    return price, delta, theta_day


# The desk prices QQQ and SPY: two spots, strikes from far in the money to far out, a quarter hour to a month, four vols.
SPOTS = [777.71, 585.3]
OFFSETS = [-50.0, -10.0, -2.0, -1.0, 0.0, 1.0, 2.0, 10.0, 50.0]
T_YEARS = [15 / (365 * 24 * 60), 1 / (365 * 24), 4 / (365 * 24), 1 / 365, 3 / 365, 30 / 365]
IVS = [0.12, 0.19, 0.30, 0.60]
KINDS = ["CALL", "PUT"]


def build() -> dict:
    # The CDF this file uses must agree with the standard library's to machine precision, or the oracle itself is wrong.
    worst = max(abs(ncdf(x / 10.0) - ND.cdf(x / 10.0)) for x in range(-80, 81))
    assert worst < 1e-15, f"erfc CDF disagrees with statistics.NormalDist by {worst}"
    rows = []
    for s in SPOTS:
        for off in OFFSETS:
            for t in T_YEARS:
                for v in IVS:
                    for kind in KINDS:
                        price, delta, theta = bs(s, s + off, t, v, kind)
                        rows.append([price, delta, theta])
    return {
        "about": "Black-Scholes r=0 from first principles (exact erfc), the oracle for src/lib/room/option-math.ts. Generated by scripts/oracle/bs_oracle.py; do not edit by hand.",
        "order": ["spot", "offset", "t", "iv", "kind"],
        "spots": SPOTS,
        "offsets": OFFSETS,
        "tYears": T_YEARS,
        "ivs": IVS,
        "kinds": KINDS,
        "columns": ["price", "delta", "thetaDay"],
        "cdfAgreementWithStatistics": "< 1e-15",
        "rows": rows,
    }


def render() -> str:
    return json.dumps(build(), separators=(",", ":")) + "\n"


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        path = __file__.replace("\\", "/").rsplit("/scripts/oracle/", 1)[0] + "/src/data/oracle-bs-grid.json"
        with open(path, "r", encoding="utf-8", newline="") as f:
            have = f.read().replace("\r\n", "\n")
        if have != text:
            sys.stderr.write("src/data/oracle-bs-grid.json is not what scripts/oracle/bs_oracle.py prints\n")
            sys.exit(1)
        print("oracle fixture is current")
    else:
        sys.stdout.write(text)
