/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronChecklistRouteImport } from './routes/api/cron/checklist'
import { Route as ApiCronExecFlattenRouteImport } from './routes/api/cron/exec-flatten'
import { Route as ApiCronRoomStepRouteImport } from './routes/api/cron/room-step'
import { Route as ApiCronReviewRouteImport } from './routes/api/cron/review'
import { Route as ApiCronWeeklyRouteImport } from './routes/api/cron/weekly'
import { Route as ApiDeskHandoffRouteImport } from './routes/api/desk/handoff'
import { Route as ApiEngineHeartbeatRouteImport } from './routes/api/engine/heartbeat'
import { Route as ApiEngineJournalRouteImport } from './routes/api/engine/journal'
import { Route as ApiRoomCycleRouteImport } from './routes/api/room/cycle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronChecklistRoute = ApiCronChecklistRouteImport.update({
  id: '/api/cron/checklist',
  path: '/api/cron/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronExecFlattenRoute = ApiCronExecFlattenRouteImport.update({
  id: '/api/cron/exec-flatten',
  path: '/api/cron/exec-flatten',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRoomStepRoute = ApiCronRoomStepRouteImport.update({
  id: '/api/cron/room-step',
  path: '/api/cron/room-step',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronReviewRoute = ApiCronReviewRouteImport.update({
  id: '/api/cron/review',
  path: '/api/cron/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronWeeklyRoute = ApiCronWeeklyRouteImport.update({
  id: '/api/cron/weekly',
  path: '/api/cron/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskHandoffRoute = ApiDeskHandoffRouteImport.update({
  id: '/api/desk/handoff',
  path: '/api/desk/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEngineHeartbeatRoute = ApiEngineHeartbeatRouteImport.update({
  id: '/api/engine/heartbeat',
  path: '/api/engine/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEngineJournalRoute = ApiEngineJournalRouteImport.update({
  id: '/api/engine/journal',
  path: '/api/engine/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomCycleRoute = ApiRoomCycleRouteImport.update({
  id: '/api/room/cycle',
  path: '/api/room/cycle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/checklist': typeof ApiCronChecklistRoute
  '/api/cron/exec-flatten': typeof ApiCronExecFlattenRoute
  '/api/cron/room-step': typeof ApiCronRoomStepRoute
  '/api/cron/review': typeof ApiCronReviewRoute
  '/api/cron/weekly': typeof ApiCronWeeklyRoute
  '/api/desk/handoff': typeof ApiDeskHandoffRoute
  '/api/engine/heartbeat': typeof ApiEngineHeartbeatRoute
  '/api/engine/journal': typeof ApiEngineJournalRoute
  '/api/room/cycle': typeof ApiRoomCycleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/checklist': typeof ApiCronChecklistRoute
  '/api/cron/exec-flatten': typeof ApiCronExecFlattenRoute
  '/api/cron/room-step': typeof ApiCronRoomStepRoute
  '/api/cron/review': typeof ApiCronReviewRoute
  '/api/cron/weekly': typeof ApiCronWeeklyRoute
  '/api/desk/handoff': typeof ApiDeskHandoffRoute
  '/api/engine/heartbeat': typeof ApiEngineHeartbeatRoute
  '/api/engine/journal': typeof ApiEngineJournalRoute
  '/api/room/cycle': typeof ApiRoomCycleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/checklist': typeof ApiCronChecklistRoute
  '/api/cron/exec-flatten': typeof ApiCronExecFlattenRoute
  '/api/cron/room-step': typeof ApiCronRoomStepRoute
  '/api/cron/review': typeof ApiCronReviewRoute
  '/api/cron/weekly': typeof ApiCronWeeklyRoute
  '/api/desk/handoff': typeof ApiDeskHandoffRoute
  '/api/engine/heartbeat': typeof ApiEngineHeartbeatRoute
  '/api/engine/journal': typeof ApiEngineJournalRoute
  '/api/room/cycle': typeof ApiRoomCycleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/api/cron/checklist'
    | '/api/cron/exec-flatten'
    | '/api/cron/room-step'
    | '/api/cron/review'
    | '/api/cron/weekly'
    | '/api/desk/handoff'
    | '/api/engine/heartbeat'
    | '/api/engine/journal'
    | '/api/room/cycle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/api/cron/checklist'
    | '/api/cron/exec-flatten'
    | '/api/cron/room-step'
    | '/api/cron/review'
    | '/api/cron/weekly'
    | '/api/desk/handoff'
    | '/api/engine/heartbeat'
    | '/api/engine/journal'
    | '/api/room/cycle'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/api/cron/checklist'
    | '/api/cron/exec-flatten'
    | '/api/cron/room-step'
    | '/api/cron/review'
    | '/api/cron/weekly'
    | '/api/desk/handoff'
    | '/api/engine/heartbeat'
    | '/api/engine/journal'
    | '/api/room/cycle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronChecklistRoute: typeof ApiCronChecklistRoute
  ApiCronExecFlattenRoute: typeof ApiCronExecFlattenRoute
  ApiCronRoomStepRoute: typeof ApiCronRoomStepRoute
  ApiCronReviewRoute: typeof ApiCronReviewRoute
  ApiCronWeeklyRoute: typeof ApiCronWeeklyRoute
  ApiDeskHandoffRoute: typeof ApiDeskHandoffRoute
  ApiEngineHeartbeatRoute: typeof ApiEngineHeartbeatRoute
  ApiEngineJournalRoute: typeof ApiEngineJournalRoute
  ApiRoomCycleRoute: typeof ApiRoomCycleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/checklist': {
      id: '/api/cron/checklist'
      path: '/api/cron/checklist'
      fullPath: '/api/cron/checklist'
      preLoaderRoute: typeof ApiCronChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/exec-flatten': {
      id: '/api/cron/exec-flatten'
      path: '/api/cron/exec-flatten'
      fullPath: '/api/cron/exec-flatten'
      preLoaderRoute: typeof ApiCronExecFlattenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/room-step': {
      id: '/api/cron/room-step'
      path: '/api/cron/room-step'
      fullPath: '/api/cron/room-step'
      preLoaderRoute: typeof ApiCronRoomStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/review': {
      id: '/api/cron/review'
      path: '/api/cron/review'
      fullPath: '/api/cron/review'
      preLoaderRoute: typeof ApiCronReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/weekly': {
      id: '/api/cron/weekly'
      path: '/api/cron/weekly'
      fullPath: '/api/cron/weekly'
      preLoaderRoute: typeof ApiCronWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk/handoff': {
      id: '/api/desk/handoff'
      path: '/api/desk/handoff'
      fullPath: '/api/desk/handoff'
      preLoaderRoute: typeof ApiDeskHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/engine/heartbeat': {
      id: '/api/engine/heartbeat'
      path: '/api/engine/heartbeat'
      fullPath: '/api/engine/heartbeat'
      preLoaderRoute: typeof ApiEngineHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/engine/journal': {
      id: '/api/engine/journal'
      path: '/api/engine/journal'
      fullPath: '/api/engine/journal'
      preLoaderRoute: typeof ApiEngineJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/room/cycle': {
      id: '/api/room/cycle'
      path: '/api/room/cycle'
      fullPath: '/api/room/cycle'
      preLoaderRoute: typeof ApiRoomCycleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronChecklistRoute: ApiCronChecklistRoute,
  ApiCronExecFlattenRoute: ApiCronExecFlattenRoute,
  ApiCronRoomStepRoute: ApiCronRoomStepRoute,
  ApiCronReviewRoute: ApiCronReviewRoute,
  ApiCronWeeklyRoute: ApiCronWeeklyRoute,
  ApiDeskHandoffRoute: ApiDeskHandoffRoute,
  ApiEngineHeartbeatRoute: ApiEngineHeartbeatRoute,
  ApiEngineJournalRoute: ApiEngineJournalRoute,
  ApiRoomCycleRoute: ApiRoomCycleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
